# Generated by Django 3.2.7 on 2021-09-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endereco',
            new_name='Enderecos',
        ),
    ]
