# Generated by Django 3.2.7 on 2021-09-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_rename_endereco_enderecos'),
        ('pontos_turisticos', '0005_pontoturistico_avaliacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='Enderecos',
            field=models.ManyToManyField(to='endereco.Enderecos'),
        ),
    ]
