# Generated by Django 3.2.7 on 2021-09-12 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_rename_endereco_enderecos'),
        ('pontos_turisticos', '0006_pontoturistico_enderecos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='Enderecos',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='enderecos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='endereco.enderecos'),
            preserve_default=False,
        ),
    ]
